# fly.toml app configuration file generated for coco-stained-glass on 2026-01-20T11:45:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coco-stained-glass'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = '/rails/bin/rails db:prepare'

[processes]
  app = '/rails/bin/rails server -p 8080'
  worker = '/rails/bin/jobs'

[env]
  HTTP_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ['worker']
